name: Release

on:
  push: {}
  pull_request: {}

jobs:
  debug_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get ARM Binutils
        run: sudo apt-get install binutils-arm-none-eabi -Y

      - name: Build the debug ELF
        run: cargo build
