name: Release

on:
  push:
    branches:
      - 'main'
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get ARM Binutils
        run: sudo apt-get install binutils-arm-none-eabi --yes

      - name: Get gbafix
        run: cargo install gbafix

      - name: Build the release ELF
        run: cargo build --release
      
      - name: Objcopy ELF into raw binary
        run: arm-none-eabi-objcopy --output-target binary target/thumbv4t-none-eabi/release/main target/zygravan.gba
      
      - name: Patch header data of raw binary
        run: gbafix target/zygravan.gba

      - name: Zip the ROM
        run: zip -9 target/zygravan target/zygravan.gba

      - name: publish release
        uses: softprops/action-gh-release@v1
        with:
          files: target/zygravan.zip
          name: ${{ env.GITHUB_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
